import time
import asyncio
from typing import List, Dict, Any, AsyncGenerator
from fastapi import FastAPI, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

app = FastAPI(title="Coverage Chatbot API")

session_store: Dict[str, List[Dict[str, str]]] = {}

class ChatRequest(BaseModel):
    session_id: str
    member_id: str
    message: str

def generate_tokens(message: str) -> List[str]:
    """Simulate tokens generated by the LLM stream."""
    msg_lower = message.lower()
    if "copay" in msg_lower:
        text = "Your copay for primary care visits is $20 under the Gold plan. This is not medical advice."
    elif "deductible" in msg_lower:
        text = "Your remaining annual individual deductible is $500. This is not medical advice."
    elif "maternity" in msg_lower or "covered" in msg_lower:
        text = "Maternity care services are covered subject to your plan deductible and copays. This is not medical advice."
    else:
        text = "Thank you for reaching out. Please verify with member services for further details. This is not medical advice."
    return [word + " " for word in text.split(" ")]

async def event_generator(req: ChatRequest) -> AsyncGenerator[str, None]:
    if req.session_id not in session_store:
        session_store[req.session_id] = []
    session_store[req.session_id].append({"role": "user", "content": req.message})
    
    full_response = ""
    tokens = generate_tokens(req.message)
    for token in tokens:
        full_response += token
        # Yield SSE data line
        yield f"data: {token}\n\n"
        await asyncio.sleep(0.04)
        
    session_store[req.session_id].append({"role": "assistant", "content": full_response.strip()})

@app.post("/chat")
async def chat(req: ChatRequest):
    return StreamingResponse(
        event_generator(req),
        media_type="text/event-stream"
    )

@app.get("/history/{session_id}")
async def get_history(session_id: str):
    if session_id not in session_store:
        return {"session_id": session_id, "history": []}
    return {"session_id": session_id, "history": session_store[session_id]}